### ISSUE TITLE
Ideas for inclusion

### ISSUE THREAD

**Issue by matthewbegun** [wtjones/awesome-low-code#1]
I am going to park some ideas here, if they seem appropriate please let me know and I'll try and add them (or you can just add them). I think I have a list somewhere, but if not I'll try and start one here!

Context - there are a few other apps that are competitors to Microsoft ~~Flow~~ Power Automate. Some of them have good features that MS didn't include in P-Automate. They're mostly free, or partly free. But not completely free.

If this isn't appropriate let me know and I'll fork instead.

Thanks, Matt

---

- IFTTT
- Zapier

**Comment by matthewbegun** [comment]
Google has a framework as well - [starthinker](https://github.com/google/starthinker) - focussed on advertising and using the gcloud ecosystem. Possibly not awesome.

**Comment by wtjones** [comment]
No need to fork - this exactly what I am looking for. 

As for starthinker, it looks like an internal tool, but maybe it is awesome? I wonder if they intended to make it more generic initially:

> Framework for building data workflows provided by Google.
